Team: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: varchar(50)
  sum: decimal
  country: varchar(100)
}

Sportsman: {
  shape: sql_table
  id: int {constraint: primary_key}
  surname: varchar(30)
  name: varchar(25)
  patronymic: varchar(30)
  teamId: int {constraint: foreign_key}
  numberInTeam: int
  birthday: date
}

CompetitionType: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: varchar(100)
  description: text
  typeId: int {constraint: foreign_key}
}

Competition: {
  shape: sql_table
  id: int {constraint: primary_key}
  name: varchar(100)
  dateOf: date
}

Patricipation: {
  shape: sql_table
  id: int {constraint: primary_key}
  competitionId: int {constraint: foreign_key}
  sportsmanId: int {constraint: foreign_key}
  place: int
  mark: decimal
}

Team.id <-> Sportsman.teamId: {
  source-arrowhead: {
    shape: cf-one
  }
  target-arrowhead: {
    shape: cf-many
  }
}

CompetitionType.id <-> Competition.id: {
  source-arrowhead: {
    shape: cf-one
  }
  target-arrowhead: {
    shape: cf-many
  }
}

Patricipation.id <-> Competition.id: {
  source-arrowhead: {
    shape: cf-one
  }
  target-arrowhead: {
    shape: cf-one
  }
}

Patricipation.id <-> Sportsman.id: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one
  }
}
